// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_management.Data;

#nullable disable

namespace library_management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260621055217_ChangeUserEntityName")]
    partial class ChangeUserEntityName
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookMember", b =>
                {
                    b.Property<string>("FavoriteBooksId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("FavoriteBooksId", "MemberId");

                    b.HasIndex("MemberId");

                    b.ToTable("FavoriteBooks", (string)null);
                });

            modelBuilder.Entity("BorrowedBook", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LibraryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MemberId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MemberId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("IdempotencyRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LibrarianId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("library_management.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("MemberId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("MemberId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.HasBaseType("Person");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("LibraryUser", b =>
                {
                    b.HasBaseType("Person");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasDiscriminator().HasValue("LibraryUser");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.HasBaseType("Person");

                    b.Property<string>("LibraryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("MembershipStart")
                        .HasColumnType("datetime(6)");

                    b.HasIndex("LibraryId");

                    b.HasIndex("NationalCode", "LibraryId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("Member");
                });

            modelBuilder.Entity("BookMember", b =>
                {
                    b.HasOne("library_management.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("FavoriteBooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Member", null)
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BorrowedBook", b =>
                {
                    b.HasOne("library_management.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library", "Library")
                        .WithMany("LentBooks")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Member", "Member")
                        .WithMany()
                        .HasForeignKey("MemberId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Library");

                    b.Navigation("Member");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.HasOne("Person", "Librarian")
                        .WithMany()
                        .HasForeignKey("LibrarianId");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.HasOne("LibraryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("library_management.Entities.Book", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("WrittenBooks")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Library", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId");

                    b.HasOne("Member", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("MemberId");

                    b.Navigation("Author");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.HasOne("Library", "Library")
                        .WithMany("Members")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("LentBooks");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("WrittenBooks");
                });

            modelBuilder.Entity("Member", b =>
                {
                    b.Navigation("BorrowedBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
