// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_management.Data;

#nullable disable

namespace library_management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260719055414_UpdateWalletEntities")]
    partial class UpdateWalletEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BookLibraryUser", b =>
                {
                    b.Property<string>("FavoriteBooksId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryUserId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("FavoriteBooksId", "LibraryUserId");

                    b.HasIndex("LibraryUserId");

                    b.ToTable("FavoriteBooks", (string)null);
                });

            modelBuilder.Entity("BorrowedBook", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LibraryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("LibraryUserId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("IdempotencyRecord", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("IdempotencyRecords");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LibrarianId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("LibrarySubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("MonthlyCost")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("SubscriptionType")
                        .HasColumnType("int");

                    b.Property<decimal>("YearlyCost")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("LibrarySubscriptions");
                });

            modelBuilder.Entity("PaymentInvoice", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DestinationWalletId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("SubscriptionId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("method")
                        .HasColumnType("int");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PaymentInvoices");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("People");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PersonId");

                    b.ToTable("PersonRoles");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("UserSubscription", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("AutoRenewal")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("BillingPeriod")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LibrarySubscriptionId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryUserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LibrarySubscriptionId");

                    b.HasIndex("LibraryUserId");

                    b.ToTable("UserSubscriptions");
                });

            modelBuilder.Entity("Wallet", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.HasKey("Id");

                    b.ToTable("Wallets");

                    b.HasDiscriminator().HasValue("Wallet");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("WalletTransaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(65,30)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<string>("WalletId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("WalletId");

                    b.ToTable("WalletTransactions");
                });

            modelBuilder.Entity("library_management.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("LibraryUserId");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.HasBaseType("Person");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("LibraryUser", b =>
                {
                    b.HasBaseType("Person");

                    b.Property<string>("HashedPassword")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LibraryId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("MembershipStart")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasIndex("LibraryId");

                    b.HasIndex("NationalCode", "LibraryId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("LibraryUser");
                });

            modelBuilder.Entity("LibraryWallet", b =>
                {
                    b.HasBaseType("Wallet");

                    b.Property<string>("LibraryId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasIndex("LibraryId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("LibraryWallet");
                });

            modelBuilder.Entity("PersonWallet", b =>
                {
                    b.HasBaseType("Wallet");

                    b.Property<string>("PersonId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasIndex("PersonId")
                        .IsUnique();

                    b.HasDiscriminator().HasValue("PersonWallet");
                });

            modelBuilder.Entity("BookLibraryUser", b =>
                {
                    b.HasOne("library_management.Entities.Book", null)
                        .WithMany()
                        .HasForeignKey("FavoriteBooksId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryUser", null)
                        .WithMany()
                        .HasForeignKey("LibraryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BorrowedBook", b =>
                {
                    b.HasOne("library_management.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library", "Library")
                        .WithMany("LentBooks")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryUser", "LibraryUser")
                        .WithMany()
                        .HasForeignKey("LibraryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Book");

                    b.Navigation("Library");

                    b.Navigation("LibraryUser");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.HasOne("Person", "Librarian")
                        .WithMany()
                        .HasForeignKey("LibrarianId");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("LibrarySubscription", b =>
                {
                    b.HasOne("Library", "Library")
                        .WithMany("LibrarySubscriptionPlan")
                        .HasForeignKey("LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("PaymentInvoice", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("PersonRole", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithMany("Roles")
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("RefreshToken", b =>
                {
                    b.HasOne("LibraryUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UserSubscription", b =>
                {
                    b.HasOne("LibrarySubscription", "LibrarySubscription")
                        .WithMany()
                        .HasForeignKey("LibrarySubscriptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LibraryUser", "LibraryUser")
                        .WithMany("Subscriptions")
                        .HasForeignKey("LibraryUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LibrarySubscription");

                    b.Navigation("LibraryUser");
                });

            modelBuilder.Entity("WalletTransaction", b =>
                {
                    b.HasOne("Wallet", "Wallet")
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Wallet");
                });

            modelBuilder.Entity("library_management.Entities.Book", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("WrittenBooks")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Library", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId");

                    b.HasOne("LibraryUser", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("LibraryUserId");

                    b.Navigation("Author");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("LibraryUser", b =>
                {
                    b.HasOne("Library", "Library")
                        .WithMany("Members")
                        .HasForeignKey("LibraryId");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("LibraryWallet", b =>
                {
                    b.HasOne("Library", "Library")
                        .WithOne("Wallet")
                        .HasForeignKey("LibraryWallet", "LibraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Library");
                });

            modelBuilder.Entity("PersonWallet", b =>
                {
                    b.HasOne("Person", "Person")
                        .WithOne("Wallet")
                        .HasForeignKey("PersonWallet", "PersonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("LentBooks");

                    b.Navigation("LibrarySubscriptionPlan");

                    b.Navigation("Members");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("Roles");

                    b.Navigation("Wallet")
                        .IsRequired();
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("WrittenBooks");
                });

            modelBuilder.Entity("LibraryUser", b =>
                {
                    b.Navigation("BorrowedBooks");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
