// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using library_management.Data;

#nullable disable

namespace library_management.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260604143153_BaseClassesUpdate")]
    partial class BaseClassesUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("BorrowedBook", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("BookId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LibraryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("BookId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("PersonId");

                    b.ToTable("BorrowedBooks");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LibrarianId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("LibrarianId");

                    b.ToTable("Libraries");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Address")
                        .HasColumnType("longtext");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("varchar(8)");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext");

                    b.Property<string>("LibraryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("NationalCode")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("LibraryId");

                    b.ToTable("People");

                    b.HasDiscriminator().HasValue("Person");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("library_management.Entities.Book", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("AuthorId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LibraryId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("PersonId1")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("LibraryId");

                    b.HasIndex("PersonId");

                    b.HasIndex("PersonId1");

                    b.ToTable("Books");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.HasBaseType("Person");

                    b.HasDiscriminator().HasValue("Author");
                });

            modelBuilder.Entity("BorrowedBook", b =>
                {
                    b.HasOne("library_management.Entities.Book", "Book")
                        .WithMany()
                        .HasForeignKey("BookId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Library", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("LibraryId");

                    b.HasOne("Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId");

                    b.Navigation("Book");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.HasOne("Person", "Librarian")
                        .WithMany()
                        .HasForeignKey("LibrarianId");

                    b.Navigation("Librarian");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.HasOne("Library", null)
                        .WithMany("Members")
                        .HasForeignKey("LibraryId");
                });

            modelBuilder.Entity("library_management.Entities.Book", b =>
                {
                    b.HasOne("Author", "Author")
                        .WithMany("WrittenBooks")
                        .HasForeignKey("AuthorId");

                    b.HasOne("Library", "Library")
                        .WithMany("Books")
                        .HasForeignKey("LibraryId");

                    b.HasOne("Person", null)
                        .WithMany("BorrowedBooks")
                        .HasForeignKey("PersonId");

                    b.HasOne("Person", null)
                        .WithMany("FavoriteBooks")
                        .HasForeignKey("PersonId1");

                    b.Navigation("Author");

                    b.Navigation("Library");
                });

            modelBuilder.Entity("Library", b =>
                {
                    b.Navigation("Books");

                    b.Navigation("BorrowedBooks");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Person", b =>
                {
                    b.Navigation("BorrowedBooks");

                    b.Navigation("FavoriteBooks");
                });

            modelBuilder.Entity("Author", b =>
                {
                    b.Navigation("WrittenBooks");
                });
#pragma warning restore 612, 618
        }
    }
}
